### PR TITLE
Add libxml2 libxslt-dev packages, fixes sparklemotion/nokogiri#1620

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by flavorjones** [comment]
Hi! Thanks for submitting this PR.

This section of the documentation is addressing the case where someone is using Nokogiri's vendored `libxml2` and `libxslt` libraries. In this case, it's not appropriate to instruct a user to install `libxml2-dev` and `libxslt-dev`.

Does that make sense?

Are you trying to address the situation where people want to install a system library but don't know what to install? If so, maybe we can talk about adding a subsection to the "Using Your System Libraries" section?

**Comment by fulldecent** [comment]
Thank you, this makes sense. I have moved the note to that section. Others PRs coming, but I will keep them separate.

**Comment by fulldecent** [comment]
@flavorjones I've given you a few PR to consider, depending on how big a change you are willing to accept to the installation instructions.

**Comment by fulldecent** [comment]
I am closing this PR in favor of #53 and #54. Both of those are more ambitious changes.

**Comment by fulldecent** [comment]
Thanks for your feedback!

**Pull request closed without merging**
