### PR TITLE
Rewrite install instructions

### PR DESCRIPTION
**Pull request by fulldecent**
* Remove duplicate content (seven copies of "please open an issue if ...")
* Remove negative language ("we have a reputation of being difficult")
* Put recommended options BEFORE other options
* Do not assume users already have developer tools installed
* Remove old information, link to prior version of that file

Surely this could be improved, but I think this is good enough to merge now since it is a significant improvement to current version.

### CODE REVIEW

**Comment by fulldecent** [comment]
Ping.

Please let me know your feedback and whether you think there are valuable improvements in here.

If so, please let me know what else I can do to get this merged 👏

**Comment by fulldecent** [comment]
Bump.

To be clear, does this improve things, and if so is this PR in scope to be merged?

**Comment by fulldecent** [comment]
Hello @flavorjones can you please confirm if this change is in scope for the project?

**Comment by fulldecent** [comment]
At this point I'm just writing this documentation for myself because I've forgotten how to install Nokogiri so many times this is getting ridiculous.

**Comment by flavorjones** [comment]
Sorry for the delay. These changes look great, thanks so much for taking the time to edit it down for brevity and clarity, and for your patience.

Merging and deploying ...

**Pull request merged**
